/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.papernews

import javafx.application.Application
import javafx.stage.Stage
import org.isen.papernews.ctrl.PaperController
import org.isen.papernews.model.impl.PaperModel
import org.isen.papernews.view.impl.PaperSearchView

class App: Application() {
    val paperModel = PaperModel()
    val paperCtrl = PaperController(paperModel)
    val papersearch = PaperSearchView(paperCtrl)
    override fun start(primaryStage: Stage) {
        this.paperCtrl.displayView()
        this.paperCtrl.loadPaperInformation()
    }
}

fun main() {
    Application.launch(App::class.java)
}