/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.isen.papernews

import org.isen.papernews.ctrl.PaperController
import org.isen.papernews.model.impl.PaperModel
import org.isen.papernews.view.impl.PaperSearchView

fun main() {
    val paperModel= PaperModel()
    val paperCtrl = PaperController(paperModel)
    val paperSearch = PaperSearchView(paperCtrl)

    paperCtrl.displayView()
    paperCtrl.loadPaperInformation()


}
